[build-system]
requires = ["setuptools", "wheel", "torch", "ninja"]
build-backend = "setuptools.build_meta"

[project]
name = "ascend_ops"
version = "0.1.0"
description = "Python interface for ascend_ops"
readme = "README.md"
dependencies = [
    "torch",
    "ninja",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["ascend_ops*"]

[tool.setuptools.package-data]
"ascend_ops" = [
    "**/*.cpp",
    "**/*.h",
]