/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file matmul_all_reduce_tiling_key.h
 * \brief
 */

#ifndef MATMUL_ALL_REDUCE_TILING_KEY_H
#define MATMUL_ALL_REDUCE_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

// AICORE_TYPE
#define ASCEND_910B 0
#define ASCEND_310P 1

// MM_TYPE
#define MATMUL_ALLREDUCE_MM_TYPE_FP_MM 0
#define MATMUL_ALLREDUCE_MM_TYPE_FP_MM_CUBE_ONLY 1
#define MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL 2
#define MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL 3

// 通用参数
#define TPL_PARAMS_COMM bool EMPTY_INPUT, bool INT8_COMM, bool ENABLE_L2_CACHE
#define PARAMS_COMM EMPTY_INPUT, INT8_COMM, ENABLE_L2_CACHE

// EMPTY_INPUT
#define MATMUL_ALLREDUCE_EMPTY_INPUT_F 0
#define MATMUL_ALLREDUCE_EMPTY_INPUT_T 1

// INT8_COMM
#define  MATMUL_ALLREDUCE_INT8_COMM_F 0
#define  MATMUL_ALLREDUCE_INT8_COMM_T 1

// matmul 类公共模板参数(预留)
#define TPL_PARAMS_SHARE_MM bool SHARE_MM
#define PARAMS_SHARE_MM SHARE_MM

// mat_mul_v3 模板参数簇
#define TPL_PARAMS_FP_MM int MIXND2NZ
#define PARAMS_FP_MM MIXND2NZ

#define MAT_MUL_V3_MIXND2NZ_TRUE 0  // MIXND2NZ
#define MAT_MUL_V3_MIXND2NZ_FALSE 1
#define MAT_MUL_V3_MIXND2NZ_TRUE_PARALLEL 2

// quant_batch_matmul_v3 模板参数簇
#define TPL_PARAMS_QUANT_MM int TRANS, int PERTOKEN
#define PARAMS_QUANT_MM TRANS, PERTOKEN

#define QUANT_BATCH_MATMUL_V3_NOT_TRANS 0   // TRANS
#define QUANT_BATCH_MATMUL_V3_B_TRANS 1
#define QUANT_BATCH_MATMUL_V3_A_TRANS 2
#define QUANT_BATCH_MATMUL_V3_ALL_TRANS 3

#define QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN 0
#define QUANT_BATCH_MATMUl_V3_IS_PERTOKEN 1

// weight_quant_batch_matmul_v2 模板参数簇
#define TPL_PARAMS_WEIGHT_QUANT_MM                              \
    int SUB_ALGORITHM_CUSTOM, bool HAS_ANTIQUANT_OFFSET,        \
    int ANTIQUANT_TYPE, bool TRANS_A, bool TRANS_B, bool FORMAT_B
#define PARAMS_WEIGHT_QUANT_MM                                  \
    SUB_ALGORITHM_CUSTOM, HAS_ANTIQUANT_OFFSET, ANTIQUANT_TYPE, \
    TRANS_A, TRANS_B, FORMAT_B

#define WQBMMV2_SUB_ALGO_SERIAL 0 // 算法小类-传统CUSTOM
#define WQBMMV2_SUB_ALGO_GENERAL_PARALLEL 1
#define WQBMMV2_SUB_ALGO_SPLIT_K_CUSTOM 2
#define WQBMMV2_SUB_ALGO_CUSTOM_ANTIQUANT 3
#define WQBMMV2_SUB_ALGO_MSD_MULTI_CORE 6
#define WQBMMV2_SUB_ALGO_MSD_GROUP 7
#define WQBMMV2_SUB_ALGO_WEIGHT_NZ 8
#define WQBMMV2_SUB_ALGO_MIX_SPLIT_K 9
#define WQBMMV2_SUB_ALGO_ANTI_REG 10

#define WQBMMV2_ANTIQUANT_TYPE_NONE 0 // 反量化类型
#define WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR 1
#define WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL 2
#define WQBMMV2_ANTIQUANT_TYPE_PER_GROUP 3
#define WQBMMV2_ANTIQUANT_TYPE_MX 4

#define PLACEHOLDER_0 0 // placehoder
#define PLACEHOLDER_1 1
#define PLACEHOLDER_2 2
#define PLACEHOLDER_3 3
#define PLACEHOLDER_4 4
#define PLACEHOLDER_5 5

// FORMAT_B_NZ
#define FORMAT_B_ND 0
#define FORMAT_B_NZ 1

// 设置tilingkey时各个MM类别的占位宏
#define SET_NOT_USE_FM_MM_TPL_TILING 0UL
#define SET_NOT_USE_QUANT_MM_TPL_TILING 0UL, 0UL
#define SET_NOT_USE_WEIGHT_QUANT_MM_TPL_TILING 0UL, 0, 0UL, 0, 0, 0

#define SET_NOT_USE_PARAM 0UL

ASCENDC_TPL_ARGS_DECL(
    MatmulAllReduce,
    // AICORE_TYPE
    ASCENDC_TPL_UINT_DECL(AICORE_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, ASCEND_910B, ASCEND_310P),
    // MM_TYPE
    ASCENDC_TPL_UINT_DECL(MM_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
    MATMUL_ALLREDUCE_MM_TYPE_FP_MM, MATMUL_ALLREDUCE_MM_TYPE_FP_MM_CUBE_ONLY, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL,
    MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
    // TPL_PARAMS_COMM
    ASCENDC_TPL_BOOL_DECL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
    ASCENDC_TPL_BOOL_DECL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F, MATMUL_ALLREDUCE_INT8_COMM_T),
    ASCENDC_TPL_BOOL_DECL(ENABLE_L2_CACHE, 0, 1),
    // TPL_PARAMS_SHARE_MM
    ASCENDC_TPL_BOOL_DECL(SHARE_MM, 0),
    // TPL_PARAMS_FP_MM
    ASCENDC_TPL_UINT_DECL(
        MIXND2NZ, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        MAT_MUL_V3_MIXND2NZ_TRUE, MAT_MUL_V3_MIXND2NZ_FALSE, MAT_MUL_V3_MIXND2NZ_TRUE_PARALLEL),

    // quant_batch_matmul_v3
    ASCENDC_TPL_UINT_DECL(
        TRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUL_V3_NOT_TRANS, QUANT_BATCH_MATMUL_V3_B_TRANS,
        QUANT_BATCH_MATMUL_V3_A_TRANS, QUANT_BATCH_MATMUL_V3_ALL_TRANS),
    ASCENDC_TPL_UINT_DECL(
        PERTOKEN, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
        QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
        QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),

    // weight_quant_batch_matmul_v2
    ASCENDC_TPL_UINT_DECL( // 算法小类-传统CUSTOM
        SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_SUB_ALGO_SERIAL,
        WQBMMV2_SUB_ALGO_GENERAL_PARALLEL,
        WQBMMV2_SUB_ALGO_SPLIT_K_CUSTOM,
        WQBMMV2_SUB_ALGO_CUSTOM_ANTIQUANT,
        PLACEHOLDER_4,
        PLACEHOLDER_5,
        WQBMMV2_SUB_ALGO_MSD_MULTI_CORE,
        WQBMMV2_SUB_ALGO_MSD_GROUP,
        WQBMMV2_SUB_ALGO_WEIGHT_NZ,
        WQBMMV2_SUB_ALGO_MIX_SPLIT_K,
        WQBMMV2_SUB_ALGO_ANTI_REG),
    ASCENDC_TPL_BOOL_DECL( // 可选输入
        HAS_ANTIQUANT_OFFSET, 0, 1),
    ASCENDC_TPL_UINT_DECL( // 反量化类型
        ANTIQUANT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
        WQBMMV2_ANTIQUANT_TYPE_NONE,
        WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
        WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL,
        WQBMMV2_ANTIQUANT_TYPE_PER_GROUP,
        WQBMMV2_ANTIQUANT_TYPE_MX),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_A, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_B, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        FORMAT_B, FORMAT_B_ND, FORMAT_B_NZ),
);

// set to default when this MM Type not needed
// in this, 0 has no meaning
#define SET_NOT_USE_FP_MM_TPL_SEL                                                       \
    ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST,0)

#define SET_NOT_USE_QUANT_MM_TPL_SEL                                                    \
    ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,0),                                 \
    ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,0)

#define SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL                                             \
    ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, 0),                 \
    ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),                                      \
    ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, 0),                       \
    ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),                                                   \
    ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),                                                   \
    ASCENDC_TPL_BOOL_SEL(FORMAT_B, 0)

ASCENDC_TPL_SEL(
#if defined(__CCE_AICORE__) && __CCE_AICORE__ < 220
//310 Kernel不支持ASCENDC_TPL_KERNEL_TYPE_SEL
// 310P quant
// result : 9
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL), // tiling_key num = 1
// 310P weightQuant
// results: [136314893, 169869325, 138412045, 171966477, 137363469, 170917901, 139460621, 173015053]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET,0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
            WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 8
// 310P unquant
// results: [134217729, 134217985]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST, MAT_MUL_V3_MIXND2NZ_TRUE, MAT_MUL_V3_MIXND2NZ_FALSE),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)),  // tiling_key num = 2
// 310P genreal
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM, 
            MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0, 1),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE,
            WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
            WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 1),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_ND)),
// empty_tensor unquant MM
// results: [134217745]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 1

// empty_tensor general MM
// results: [17]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL), // tiling_key num = 1

// empty_tensor WQBMM_NZ
// results: [134217757]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 1
#else

// 310P quant
// result : 9
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL), // tiling_key num = 1
// 310P weightQuant
// results: [136314893, 169869325, 138412045, 171966477, 137363469, 170917901, 139460621, 173015053]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET,0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
            WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 8
// 310P unquant
// results: [134217729, 134217985]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST, MAT_MUL_V3_MIXND2NZ_TRUE, MAT_MUL_V3_MIXND2NZ_FALSE),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)),  // tiling_key num = 2
// 310P genreal
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM, 
            MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0, 1),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE,
            WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
            WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 1),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_ND)),
// empty_tensor unquant MM
// results: [134217745]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 1

// empty_tensor general MM
// results: [17]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL), // tiling_key num = 1

// empty_tensor WQBMM_NZ
// results: [134217757]
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_310P),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, SET_NOT_USE_PARAM),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_NONE),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_NZ)), // tiling_key num = 1

// empty_tensor MM/WQBMM
    // tiling_key num = 1
    // 16
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIV_1_0),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),

     // tiling_key num = 1
     // 28
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIV_1_0),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST,
            MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_T),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),

// MATMUL_ALLREDUCE_MM_TYPE_FP_MM
    // tiling_key num = 1
    // 260
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_0),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM_CUBE_ONLY),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST, MAT_MUL_V3_MIXND2NZ_FALSE),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),

    // not empty_tensor not CUBEONLY
    // tiling_key num = 2
    // 256, 0
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST,
            MAT_MUL_V3_MIXND2NZ_FALSE,
            MAT_MUL_V3_MIXND2NZ_TRUE),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),

// MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL
    // tiling_key num = 8
    // 4104(1), 20488, 8(0), 16392, 4136, 20520, 40, 16424
#if defined(__CCE_AICORE__) && __CCE_AICORE__ == 220
#if ((ORIG_DTYPE_X1 == DT_INT8) && (ORIG_DTYPE_Y == DT_BF16 || ORIG_DTYPE_RESIDUAL == DT_BF16))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_T),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
#elif ((ORIG_DTYPE_X1 == DT_INT8) && (ORIG_DTYPE_Y == DT_FLOAT16 || ORIG_DTYPE_RESIDUAL == DT_FLOAT16))
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),

    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_T),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
#else
    // for host or not quant
    // Not used on kernel
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_F,
            MATMUL_ALLREDUCE_INT8_COMM_T),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
#endif
#else //defined(__CCE_AICORE__) && __CCE_AICORE__ == 220
    // for host or not quant
    // Not used on kernel
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,
            MATMUL_ALLREDUCE_INT8_COMM_F,
            MATMUL_ALLREDUCE_INT8_COMM_T),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUL_V3_B_TRANS,
            QUANT_BATCH_MATMUL_V3_NOT_TRANS),
        ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST,
            QUANT_BATCH_MATMUl_V3_NOT_PERTOKEN,
            QUANT_BATCH_MATMUl_V3_IS_PERTOKEN),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL),
#endif//defined(__CCE_AICORE__) && __CCE_AICORE__ == 220

// MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL

    // tiling_key num = 12
    // 2293772, 69402636, 4390924, 71499788, 6488076, 73596940, 3342348, 70451212, 5439500, 72548364, 7536652, 74645516
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM, MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_CUSTOM_ANTIQUANT),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST,
            WQBMMV2_ANTIQUANT_TYPE_PER_TENSOR,
            WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL,
            WQBMMV2_ANTIQUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_ND)),
    // tiling_key num = 4
    // 4718604, 71827468, 5767180, 72876044
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(AICORE_TYPE, ASCENDC_TPL_UI_LIST,
            ASCEND_910B),
        ASCENDC_TPL_UINT_SEL(MM_TYPE, ASCENDC_TPL_UI_LIST, MATMUL_ALLREDUCE_MM_TYPE_WEIGHT_QUANT_MATMUL),
        ASCENDC_TPL_BOOL_SEL(EMPTY_INPUT, MATMUL_ALLREDUCE_EMPTY_INPUT_F),
        ASCENDC_TPL_BOOL_SEL(INT8_COMM,MATMUL_ALLREDUCE_INT8_COMM_F),
        ASCENDC_TPL_BOOL_SEL(ENABLE_L2_CACHE, 0),
        ASCENDC_TPL_BOOL_SEL(SHARE_MM, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(SUB_ALGORITHM_CUSTOM, ASCENDC_TPL_UI_LIST, WQBMMV2_SUB_ALGO_WEIGHT_NZ),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, WQBMMV2_ANTIQUANT_TYPE_PER_CHANNEL),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0),
        ASCENDC_TPL_BOOL_SEL(TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(FORMAT_B, FORMAT_B_ND)),
#endif
);

#endif // MATMUL_ALL_REDUCE_TILING_KEY_H