/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file matmul_all_reduce_apt_tiling_key.h
 * \brief
 */

#ifndef MATMUL_ALL_REDUCE_APT_TILING_KEY_H
#define MATMUL_ALL_REDUCE_APT_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"
#include "arch35/matmul_all_reduce_tiling_struct_ar35.h"
// APT_MM_TYPE
#define MMTYPE_FP_NULL_TENSOR 0
#define MMTYPE_FP_MM 1
#define MMTYPE_QUANT_MM 2
#define MMTYPE_WEIGHT_QUANT_MM 3
#define MMTYPE_WEIQUANT_NULL_TENSOR 4

// 通用参数
#define TPL_APT_PARAMS_COMM bool TPL_TRANS_B, bool TPL_EXIST_BIAS
#define APT_PARAMS_COMM TPL_TRANS_B, TPL_EXIST_BIAS
#define TPL_APT_A2A_RS_AG bool TPL_A2A_RS_AG
#define APT_A2A_RS_AG TPL_A2A_RS_AG

// fp_matmul_all_reduce 模板参数簇
#define TPL_APT_PARAMS_FP_MM bool MATMUL_WITH_ADD
#define APT_PARAMS_FP_MM MATMUL_WITH_ADD

// quant_matmul_all_reduce 模板参数簇
#define TPL_APT_PARAMS_QUANT_MM uint64_t KERNEL_TYPE, uint8_t COMMDTPYE, \
                                bool SCENARIO_MXFP8
#define APT_PARAMS_QUANT_MM KERNEL_TYPE, COMMDTPYE, \
                            SCENARIO_MXFP8

#define COMMDTPYE_DEFAULT 0 // COMMDTPYE
#define COMMDTPYE_INT8 1
#define COMMDTPYE_FP8 2

#define NO_VEC_EPILOGUE_WITH_MMAPI 0 // KERNEL_TYPE
#define NO_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI 1
#define VEC_EPILOGUE_WITH_MMAPI 2
#define VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI 3
#define VEC_EPILOGUE_WITH_CUSTOM_MM 4

// weight_quant_matmul_allreduce 模板参数簇
#define TPL_APT_PARAMS_WEIGHT_QUANT_MM uint8_t TEMPLATE_CUSTOM, uint8_t ANTIQUANT_TYPE, \
                                uint8_t QUANTTYPE, bool HAS_ANTIQUANT_OFFSET, \
                                bool BAIS_IS_FP32, uint8_t WEIGHTFORMAT
#define APT_PARAMS_WEIGHT_QUANT_MM TEMPLATE_CUSTOM, ANTIQUANT_TYPE, \
                            QUANTTYPE, HAS_ANTIQUANT_OFFSET, \
                            BAIS_IS_FP32, WEIGHTFORMAT

#define TPL_MTE2_INNER_SIZE_512_BUF_NUM_2 0 // TEMPLATE_CUSTOM
#define TPL_MTE2_INNER_SIZE_512_BUF_NUM_4 1
#define TPL_MTE2_INNER_SIZE_1024_BUF_NUM_2 2
#define TPL_MTE2_INNER_SIZE_256_BUF_NUM_4 3
#define TPL_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT 4

#define TPL_PER_QUANT_DEFAULT 0 // ANTIQUANT_TYPE
#define TPL_PER_TENSOR 1
#define TPL_PER_CHANNEL 2
#define TPL_PER_GROUP 3

#define TPL_QUANTTYPE_DEFAULT 0 // QUANTTYPE
#define TPL_QUANTTYPE_PER_TENSOR 1

#define TPL_ND 0 // WEIGHTFORMAT

// 设置获取tilingkey时各类别的占位宏
#define SET_NOT_USE_FP_MM_TILING 0
#define SET_NOT_USE_QUANT_MM_TILING 0UL, 0UL, 0
#define SET_NOT_USE_WEIGHT_QUANT_MM_TILING 0UL, 0UL, 0UL, 0, 0, 0UL

ASCENDC_TPL_ARGS_DECL(
    Mc2MatmulAllReduceApt,
    // APT_MM_TYPE
    ASCENDC_TPL_UINT_DECL(APT_MM_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, \
                        MMTYPE_FP_NULL_TENSOR, MMTYPE_FP_MM, \
                        MMTYPE_QUANT_MM, MMTYPE_WEIGHT_QUANT_MM, MMTYPE_WEIQUANT_NULL_TENSOR),
    // TPL_PARAMS_COMM
    ASCENDC_TPL_BOOL_DECL(TPL_TRANS_B, 0, 1),
    ASCENDC_TPL_BOOL_DECL(TPL_EXIST_BIAS, 0, 1),
    ASCENDC_TPL_BOOL_DECL(TPL_A2A_RS_AG, 0, 1),
    // quant_matmul_all_reduce
    ASCENDC_TPL_BOOL_DECL(MATMUL_WITH_ADD, 0, 1),
    // quant_matmul_all_reduce
    ASCENDC_TPL_UINT_DECL(KERNEL_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, \
                        NO_VEC_EPILOGUE_WITH_MMAPI, NO_VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI, \
                        VEC_EPILOGUE_WITH_MMAPI, VEC_EPILOGUE_CUSTOM_GMTOAL1_WITH_MMAPI, \
                        VEC_EPILOGUE_WITH_CUSTOM_MM),
    ASCENDC_TPL_UINT_DECL(COMMDTPYE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        COMMDTPYE_DEFAULT, COMMDTPYE_INT8, COMMDTPYE_FP8),
    ASCENDC_TPL_BOOL_DECL(SCENARIO_MXFP8, 0, 1),
    // weight_quant_matmul_allreduce
    ASCENDC_TPL_UINT_DECL(TEMPLATE_CUSTOM, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_MTE2_INNER_SIZE_512_BUF_NUM_2, TPL_MTE2_INNER_SIZE_512_BUF_NUM_4, \
                        TPL_MTE2_INNER_SIZE_1024_BUF_NUM_2, TPL_MTE2_INNER_SIZE_256_BUF_NUM_4, \
                        TPL_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT),
    ASCENDC_TPL_UINT_DECL(ANTIQUANT_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_PER_QUANT_DEFAULT, TPL_PER_TENSOR, TPL_PER_CHANNEL, TPL_PER_GROUP),
    ASCENDC_TPL_UINT_DECL(QUANTTYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_QUANTTYPE_DEFAULT, TPL_QUANTTYPE_PER_TENSOR),
    ASCENDC_TPL_BOOL_DECL(HAS_ANTIQUANT_OFFSET, 0, 1),
    ASCENDC_TPL_BOOL_DECL(BAIS_IS_FP32, 0, 1),
    ASCENDC_TPL_UINT_DECL(WEIGHTFORMAT, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_ND),
);

// 模板参数组合
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
#define SET_NOT_USE_FP_MM_TPL_SEL                                   \
    ASCENDC_TPL_BOOL_SEL(MATMUL_WITH_ADD, 0)

#define SET_NOT_USE_QUANT_MM_TPL_SEL                                \
    ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, 0UL),    \
    ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, 0UL),      \
    ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 0)

#define SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL                             \
    ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, 0UL),    \
    ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, 0UL),     \
    ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, 0UL),          \
    ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0),                      \
    ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 0),                              \
    ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, 0UL)

ASCENDC_TPL_SEL(
    // 空tensor场景
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIV_1_0),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_FP_NULL_TENSOR),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::MatmulAllReduce910TilingDataA5)
    ),

    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIV_1_0),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIQUANT_NULL_TENSOR),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    // fp_matmul_all_reduce
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_0),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0),
        ASCENDC_TPL_BOOL_SEL(MATMUL_WITH_ADD, 0),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::MatmulAllReduce910TilingDataA5)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 1),
        ASCENDC_TPL_BOOL_SEL(MATMUL_WITH_ADD, 0),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::MatmulAllReduce910TilingDataA5)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_FP_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        ASCENDC_TPL_BOOL_SEL(MATMUL_WITH_ADD, 1),
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::MatmulAllReduce910TilingDataA5)
    ),
    // quant_matmul_all_reduce
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, \
                            NO_VEC_EPILOGUE_WITH_MMAPI, VEC_EPILOGUE_WITH_MMAPI),
        ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, \
                            COMMDTPYE_DEFAULT, COMMDTPYE_INT8),
        ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 0),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::QuantMatmulAllReduceTilingDataA5)
    ),
    // 下面这个tilingKey模板不确定对不对
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, \
                            NO_VEC_EPILOGUE_WITH_MMAPI, VEC_EPILOGUE_WITH_MMAPI),
        ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, COMMDTPYE_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 0),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::QuantMatmulAllReduceTilingDataA5)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, VEC_EPILOGUE_WITH_CUSTOM_MM),
        ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, COMMDTPYE_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 0),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::QuantMatmulAllReduceTilingDataA5)
    ),
    // 通信为FP8场景
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, VEC_EPILOGUE_WITH_MMAPI),
        ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, COMMDTPYE_FP8),
        ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 0),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::QuantMatmulAllReduceTilingDataA5)
    ),
    // 计算方式为MXFP8场景
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(KERNEL_TYPE, ASCENDC_TPL_UI_LIST, NO_VEC_EPILOGUE_WITH_MMAPI),
        ASCENDC_TPL_UINT_SEL(COMMDTPYE, ASCENDC_TPL_UI_LIST, COMMDTPYE_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(SCENARIO_MXFP8, 1),
        SET_NOT_USE_WEIGHT_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::QuantMatmulAllReduceTilingDataA5)
    ),
    // weight_quant_matmul_allreduce
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, TPL_MTE2_INNER_SIZE_512_BUF_NUM_2),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_GROUP),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_DEFAULT),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 0),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST,                                  \
                            TPL_MTE2_INNER_SIZE_512_BUF_NUM_2, TPL_MTE2_INNER_SIZE_512_BUF_NUM_4,   \
                            TPL_MTE2_INNER_SIZE_1024_BUF_NUM_2, TPL_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 0),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST,                                  \
                            TPL_MTE2_INNER_SIZE_512_BUF_NUM_2, TPL_MTE2_INNER_SIZE_512_BUF_NUM_4,   \
                            TPL_MTE2_INNER_SIZE_1024_BUF_NUM_2, TPL_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 1),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, TPL_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_TENSOR, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 0),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, TPL_MTE2_INNER_SIZE_256_BUF_NUM_4),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_TENSOR, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 1),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, TPL_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_TENSOR, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 0),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_2),
        ASCENDC_TPL_UINT_SEL(APT_MM_TYPE, ASCENDC_TPL_UI_LIST, MMTYPE_WEIGHT_QUANT_MM),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANS_B, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_EXIST_BIAS, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_A2A_RS_AG, 0, 1),
        SET_NOT_USE_FP_MM_TPL_SEL,
        SET_NOT_USE_QUANT_MM_TPL_SEL,
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, TPL_MTE2_INNER_SIZE_512_BUF_NUM_DEFAULT),
        ASCENDC_TPL_UINT_SEL(ANTIQUANT_TYPE, ASCENDC_TPL_UI_LIST, TPL_PER_TENSOR, TPL_PER_CHANNEL),
        ASCENDC_TPL_UINT_SEL(QUANTTYPE, ASCENDC_TPL_UI_LIST, TPL_QUANTTYPE_PER_TENSOR),
        ASCENDC_TPL_BOOL_SEL(HAS_ANTIQUANT_OFFSET, 0, 1),
        ASCENDC_TPL_BOOL_SEL(BAIS_IS_FP32, 1),
        ASCENDC_TPL_UINT_SEL(WEIGHTFORMAT, ASCENDC_TPL_UI_LIST, TPL_ND),
        ASCENDC_TPL_TILING_STRUCT_SEL(Mc2Tiling::WeightQuantMatmulAllReduceA5Fp8TilingData)
    ),
);

#endif // MATMUL_ALL_REDUCE_APT_TILING_KEY_H