/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file matmul_reduce_scatter_v2_apt_tiling_key.h
 * \brief
 */

#ifndef __OP_KERNEL_MATMUL_REDUCE_SCATTER_V2_APT_TILING_KEY_H__
#define __OP_KERNEL_MATMUL_REDUCE_SCATTER_V2_APT_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

namespace Mc2Tiling{

// TPL_INPUT uint8_t
#define INPUT_TYPE_IS_FP8 0
#define INPUT_TYPE_IS_FP16_BF16 1

// TPL_OUTPUTDTYPE uint8_t
#define OUTPUT_TYPE_IS_FP16_BF16 0
#define OUTPUT_TYPE_IS_FP8 1
#define OUTPUT_TYPE_IS_FLOAT 2

// TPL_SCALETYPE uint8_t
#define TPL_X1_X2_DTYPE_IS_OTHER 0
#define TPL_X1_X2_DTYPE_IS_FP8E8M0 1

// TPL_COMMALG uint8_t
#define TPL_CCU_REDUCESUM 0
#define TPL_CCU_ALL2ALL_VEC_REDUCE 1

// 模板参数
ASCENDC_TPL_ARGS_DECL(
    Mc2MatmulReduceScatterV2, // 算子OpType
    ASCENDC_TPL_BOOL_DECL(TPL_ISPERBLOCK, 0, 1),
    ASCENDC_TPL_BOOL_DECL(TPL_TRANSA, 0, 1),
    ASCENDC_TPL_BOOL_DECL(TPL_TRANSB, 0, 1),
    ASCENDC_TPL_UINT_DECL(TPL_INPUT, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        INPUT_TYPE_IS_FP8, INPUT_TYPE_IS_FP16_BF16),
    ASCENDC_TPL_UINT_DECL(TPL_OUTPUTDTYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        OUTPUT_TYPE_IS_FP16_BF16, OUTPUT_TYPE_IS_FP8, OUTPUT_TYPE_IS_FLOAT),
    ASCENDC_TPL_UINT_DECL(TPL_SCALETYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_X1_X2_DTYPE_IS_OTHER, TPL_X1_X2_DTYPE_IS_FP8E8M0),
    ASCENDC_TPL_UINT_DECL(TPL_COMMALG, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, \
                        TPL_CCU_REDUCESUM, TPL_CCU_ALL2ALL_VEC_REDUCE),
);

// 模板参数组合
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
ASCENDC_TPL_SEL(
    // base_tiling
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(TPL_ISPERBLOCK, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSA, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSB, 0, 1),
        ASCENDC_TPL_UINT_SEL(TPL_INPUT, ASCENDC_TPL_UI_LIST, INPUT_TYPE_IS_FP16_BF16),
        ASCENDC_TPL_UINT_SEL(TPL_OUTPUTDTYPE, ASCENDC_TPL_UI_LIST, OUTPUT_TYPE_IS_FP8),
        ASCENDC_TPL_UINT_SEL(TPL_SCALETYPE, ASCENDC_TPL_UI_LIST, TPL_X1_X2_DTYPE_IS_OTHER),
        ASCENDC_TPL_UINT_SEL(TPL_COMMALG, ASCENDC_TPL_UI_LIST, \
                             TPL_CCU_REDUCESUM, TPL_CCU_ALL2ALL_VEC_REDUCE),
    ),

    // quant_bmm_tiling
    // scaletype为0
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(TPL_ISPERBLOCK, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSA, 0, 1),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSB, 0, 1),
        ASCENDC_TPL_UINT_SEL(TPL_INPUT, ASCENDC_TPL_UI_LIST, INPUT_TYPE_IS_FP8),
        ASCENDC_TPL_UINT_SEL(TPL_OUTPUTDTYPE, ASCENDC_TPL_UI_LIST, OUTPUT_TYPE_IS_FP16_BF16, \
                            OUTPUT_TYPE_IS_FLOAT),
        ASCENDC_TPL_UINT_SEL(TPL_SCALETYPE, ASCENDC_TPL_UI_LIST, TPL_X1_X2_DTYPE_IS_OTHER),
        ASCENDC_TPL_UINT_SEL(TPL_COMMALG, ASCENDC_TPL_UI_LIST, \
                             TPL_CCU_REDUCESUM, TPL_CCU_ALL2ALL_VEC_REDUCE),
    ),

    // scaletype为1
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(TPL_ISPERBLOCK, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSA, 0),
        ASCENDC_TPL_BOOL_SEL(TPL_TRANSB, 0, 1),
        ASCENDC_TPL_UINT_SEL(TPL_INPUT, ASCENDC_TPL_UI_LIST, INPUT_TYPE_IS_FP8),
        ASCENDC_TPL_UINT_SEL(TPL_OUTPUTDTYPE, ASCENDC_TPL_UI_LIST, OUTPUT_TYPE_IS_FP16_BF16, \
                            OUTPUT_TYPE_IS_FLOAT),
        ASCENDC_TPL_UINT_SEL(TPL_SCALETYPE, ASCENDC_TPL_UI_LIST, TPL_X1_X2_DTYPE_IS_FP8E8M0),
        ASCENDC_TPL_UINT_SEL(TPL_COMMALG, ASCENDC_TPL_UI_LIST, \
                             TPL_CCU_REDUCESUM, TPL_CCU_ALL2ALL_VEC_REDUCE),
    ),
);
} // matmul_reduce_scatter_v2_apt_tiling_key

#endif // __OP_KERNEL_MATMUL_REDUCE_SCATTER_V2_APT_TILING_KEY_H__