#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ======================================================================================================================

import numpy

TestCases = {
    "GQA_01": {
        "is_deter" : "FLASE",
        "B" : 1,
        "N1" : 2,
        "N2" : 1,
        "S1" : 128,
        "S2" : 128,
        "D" : 177,
        "D_V" : 177,
        "dtype" : "fp16",
        "out_dtype" : "fp16",
        "sparse_mode" : 0,
        "sparse" : "TRUE",
        "pre_tockens_input" : 65536,
        "next_tockens_input" : 65536,
        "input_layout" : "BNSD",
        "pse_type" : 1,
        "pse_shape" : "NONE",
        "atten_mask_dtype" : "NONE",
        "atten_mask_shape" : "NONE",
        "drop_out_possibility" : 1,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 0,
    },
    "MLA_02": {
        "is_deter" : "FLASE",
        "B" : 1,
        "N1" : 2,
        "N2" : 1,
        "S1" : 128,
        "S2" : 128,
        "D" : 192,
        "D_V" : 128,
        "dtype" : "fp16",
        "out_dtype" : "fp16",
        "sparse_mode" : 0,
        "sparse" : "TRUE",
        "pre_tockens_input" : 65536,
        "next_tockens_input" : 65536,
        "input_layout" : "BNSD",
        "pse_type" : 1,
        "pse_shape" : "NONE",
        "atten_mask_dtype" : "NONE",
        "atten_mask_shape" : "NONE",
        "drop_out_possibility" : 1,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 1,
    },
    "FP8E5_03": {
        "is_deter" : "FLASE",
        "B" : 2,
        "N1" : 2,
        "N2" : 1,
        "S1" : 125,
        "S2" : 125,
        "D" : 128,
        "D_V" : 128,
        "dtype" : "fp8_e5m2",
        "out_dtype" : "fp16",
        "sparse_mode" : 0,
        "sparse" : "TRUE",
        "pre_tockens_input" : 65536,
        "next_tockens_input" : 65536,
        "input_layout" : "BSND",
        "pse_type" : 1,
        "pse_shape" : "NONE",
        "atten_mask_dtype" : "NONE",
        "atten_mask_shape" : "NONE",
        "drop_out_possibility" : 1,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 0,
    },
    "FP8E4_04": {
        "is_deter" : "FLASE",
        "B" : 2,
        "N1" : 2,
        "N2" : 1,
        "S1" : 129,
        "S2" : 125,
        "D" : 128,
        "D_V" : 128,
        "dtype" : "fp8_e4m3fn",
        "out_dtype" : "bp16",
        "sparse_mode" : 0,
        "sparse" : "TRUE",
        "pre_tockens_input" : 65536,
        "next_tockens_input" : 65536,
        "input_layout" : "SBH",
        "pse_type" : 1,
        "pse_shape" : "NONE",
        "atten_mask_dtype" : "NONE",
        "atten_mask_shape" : "NONE",
        "drop_out_possibility" : 1,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 0,
    },
    "FP32_05": {
        "is_deter" : "FLASE",
        "B" : 9,
        "N1" : 8,
        "N2" : 2,
        "S1" : 80,
        "S2" : 80,
        "D" : 167,
        "D_V" : 167,
        "dtype" : "fp32",
        "out_dtype" : "fp32",
        "sparse_mode" : 0,
        "sparse" : "TRUE",
        "pre_tockens_input" : -26,
        "next_tockens_input" : 65536,
        "input_layout" : "BSND",
        "pse_type" : 3,
        "pse_shape" : "BN",
        "atten_mask_dtype" : "uint8",
        "atten_mask_shape" : "B1SS",
        "drop_out_possibility" : 1,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 0,
    },  
    "TND_06": {
        "is_deter" : "FLASE",
        "B" : 4,
        "N1" : 16,
        "N2" : 16,
        "actual_seq_qlen" : [114, 132, 14, 287],
        "actual_seq_kvlen" : [114, 132, 14, 287],
        "S1" : 287,
        "S2" : 287,
        "D" : 128,
        "D_V" : 128,
        "dtype" : "fp16",
        "out_dtype" : "fp16",
        "sparse_mode" : 3,
        "sparse" : "TRUE",
        "pre_tockens_input" : 65536,
        "next_tockens_input" : 0,
        "input_layout" : "TND",
        "pse_type" : 1,
        "pse_shape" : "1NHS",
        "atten_mask_dtype" : "BOOL",
        "atten_mask_shape" : "SS",
        "drop_out_possibility" : 0.9,
        "padding_mask" : "NONE",
        "seed" : 2,
        "offset" : 0,
        "inner_drop" : 1,
        "rope" : 0,
    },   
}