#!/usr/bin/env python3
"""
Dump a saved causal_conv1d case directory from raw `.bin` files into NumPy `.npy`
arrays for easier inspection.

It reads shapes from `meta.txt` (generated by gen_case.py) and supports:

Inputs:
  x.bin, weight.bin, bias.bin, conv_states.bin,
  query_start_loc.bin, cache_indices.bin, has_initial_state.bin

Outputs (if present):
  y_device.bin, conv_states_device.bin
  y_ref_torch.bin, conv_states_ref_torch.bin

Examples:
  python3 dump_case_npy.py --case_dir ./case --inputs
  python3 dump_case_npy.py --case_dir ./case --outputs
  python3 dump_case_npy.py --case_dir ./case --out_dir ./npy --strict
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np

F32 = np.dtype("<f4")
I32 = np.dtype("<i4")
U8 = np.dtype("u1")


def read_meta_txt(path: Path) -> Dict[str, int]:
    meta: Dict[str, int] = {}
    if not path.exists():
        return meta
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = "".join(ch for ch in raw if not ch.isspace())
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        try:
            meta[k] = int(v)
        except ValueError:
            continue
    return meta


def _numel(shape: Tuple[int, ...]) -> int:
    n = 1
    for d in shape:
        n *= int(d)
    return int(n)


def load_bin(path: Path, dtype: np.dtype, shape: Tuple[int, ...]) -> np.ndarray:
    expected = _numel(shape) * int(dtype.itemsize)
    actual = int(path.stat().st_size)
    if expected != actual:
        raise ValueError(f"Size mismatch for {path} (got {actual} bytes, expected {expected} bytes)")
    return np.fromfile(str(path), dtype=dtype).reshape(shape)


def dump_many(
    *,
    case_dir: Path,
    out_dir: Path,
    filenames: Iterable[str],
    specs: Dict[str, Tuple[np.dtype, Tuple[int, ...]]],
    strict: bool,
) -> List[Path]:
    written: List[Path] = []
    for name in filenames:
        src = case_dir / name
        if not src.exists():
            if strict:
                raise FileNotFoundError(f"Missing required file: {src}")
            continue

        if name not in specs:
            raise KeyError(f"Unknown file spec for: {name}")

        dtype, shape = specs[name]
        arr = load_bin(src, dtype, shape)
        dst = out_dir / f"{src.stem}.npy"
        np.save(str(dst), arr)
        written.append(dst)
    return written


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case_dir", type=Path, required=True)
    ap.add_argument("--out_dir", type=Path, default=None, help="Output directory (default: case_dir)")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--inputs", action="store_true", help="Dump inputs only")
    g.add_argument("--outputs", action="store_true", help="Dump outputs only")
    ap.add_argument("--strict", action="store_true", help="Fail if any requested file is missing")
    args = ap.parse_args()

    case_dir: Path = args.case_dir
    out_dir: Path = args.out_dir if args.out_dir is not None else case_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    meta = read_meta_txt(case_dir / "meta.txt")
    batch_size = int(meta.get("batch_size", 32))
    total_seqlen = int(meta.get("total_seqlen", 8192))
    dim = int(meta.get("dim", 1024))
    width = int(meta.get("width", 4))

    y_shape = (total_seqlen, dim)
    s_shape = (batch_size, width - 1, dim)

    specs: Dict[str, Tuple[np.dtype, Tuple[int, ...]]] = {
        # inputs
        "x.bin": (F32, (total_seqlen, dim)),
        "weight.bin": (F32, (width, dim)),
        "bias.bin": (F32, (dim,)),
        "conv_states.bin": (F32, s_shape),
        "query_start_loc.bin": (I32, (batch_size + 1,)),
        "cache_indices.bin": (I32, (batch_size,)),
        "has_initial_state.bin": (U8, (batch_size,)),
        # outputs
        "y_device.bin": (F32, y_shape),
        "conv_states_device.bin": (F32, s_shape),
        "y_ref_torch.bin": (F32, y_shape),
        "conv_states_ref_torch.bin": (F32, s_shape),
    }

    input_files = [
        "x.bin",
        "weight.bin",
        "bias.bin",
        "conv_states.bin",
        "query_start_loc.bin",
        "cache_indices.bin",
        "has_initial_state.bin",
    ]
    output_files = [
        "y_device.bin",
        "conv_states_device.bin",
        "y_ref_torch.bin",
        "conv_states_ref_torch.bin",
    ]

    try:
        if bool(args.inputs):
            written = dump_many(
                case_dir=case_dir,
                out_dir=out_dir,
                filenames=input_files,
                specs=specs,
                strict=bool(args.strict),
            )
        elif bool(args.outputs):
            written = dump_many(
                case_dir=case_dir,
                out_dir=out_dir,
                filenames=output_files,
                specs=specs,
                strict=bool(args.strict),
            )
        else:
            written = []
            written += dump_many(
                case_dir=case_dir,
                out_dir=out_dir,
                filenames=input_files,
                specs=specs,
                strict=False,
            )
            written += dump_many(
                case_dir=case_dir,
                out_dir=out_dir,
                filenames=output_files,
                specs=specs,
                strict=False,
            )
            if bool(args.strict):
                # In strict mode without --inputs/--outputs, require that all known files exist.
                missing = [str(case_dir / f) for f in (input_files + output_files) if not (case_dir / f).exists()]
                if missing:
                    raise FileNotFoundError("Missing required files:\n" + "\n".join(missing))
    except Exception as e:
        print(f"ERROR: {e}")
        return 2

    if not written:
        print(f"ERROR: no .bin files converted under: {case_dir}")
        return 2

    print(f"Wrote {len(written)} .npy file(s) to: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

