/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file test_aclnn_causal_conv1d.cpp
 * \brief Test example for aclnnCausalConv1d operator (Prefill/Extend mode)
 */

#include <iostream>
#include <vector>
#include <cstdint>
#include <cmath>
#include <algorithm>
#include <string>
#include <fstream>
#include <cstdlib>
#include <cerrno>
#include <limits>
#ifdef _WIN32
#include <direct.h>
#else
#include <sys/stat.h>
#endif
#include "acl/acl.h"
#include "aclnn/opdev/fp16_t.h"
#include "aclnnop/aclnn_causal_conv1d.h"

#define CHECK_RET(cond, return_expr) \
  do {                               \
    if (!(cond)) {                   \
      return_expr;                   \
    }                                \
  } while (0)

#define LOG_PRINT(message, ...)     \
  do {                              \
    printf(message, ##__VA_ARGS__); \
  } while (0)

int64_t GetShapeSize(const std::vector<int64_t>& shape) {
  int64_t shapeSize = 1;
  for (auto i : shape) {
    shapeSize *= i;
  }
  return shapeSize;
}

template <typename T>
std::vector<T> CopyDeviceToHost(const std::vector<int64_t> &shape, void* deviceAddr) {
  auto size = GetShapeSize(shape);
  std::vector<T> hostData(size, 0);
  auto ret = aclrtMemcpy(hostData.data(), hostData.size() * sizeof(hostData[0]),
                         deviceAddr, size * sizeof(hostData[0]), ACL_MEMCPY_DEVICE_TO_HOST);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("copy result from device to host failed. ERROR: %d\n", ret); return {});
  return hostData;
}

template <typename T>
void PrintFirstN(const std::string &label, const std::vector<T> &data, int64_t offset, int64_t n) {
  if (offset < 0 || offset >= static_cast<int64_t>(data.size())) {
    LOG_PRINT("%s: offset out of range (offset=%ld, size=%zu)\n", label.c_str(), offset, data.size());
    return;
  }
  const int64_t remaining = static_cast<int64_t>(data.size()) - offset;
  const int64_t limit = std::min(n, remaining);
  for (int64_t i = 0; i < limit; ++i) {
    LOG_PRINT("%s[%ld] is: %f\n", label.c_str(), i, static_cast<float>(data[static_cast<size_t>(offset + i)]));
  }
}

void PrintUsage(const char* argv0) {
  const char* prog = (argv0 != nullptr) ? argv0 : "test_aclnn_causal_conv1d";
  LOG_PRINT("Usage: %s\n", prog);
  LOG_PRINT("This example uses hard-coded shapes and reads inputs from ./case by default (generated by gen_case.py)\n");
  LOG_PRINT("Override the case directory via env: CAUSAL_CONV1D_CASE_DIR=/path/to/case\n");
  LOG_PRINT("It dumps inputs/outputs to the same case directory.\n");
  LOG_PRINT("Outputs: <case_dir>/y_device.bin, <case_dir>/conv_states_device.bin\n");
}

int Init(int32_t deviceId, aclrtStream* stream) {
  // 固定写法，AscendCL初始化
  auto ret = aclInit(nullptr);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclInit failed. ERROR: %d\n", ret); return ret);
  ret = aclrtSetDevice(deviceId);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclrtSetDevice failed. ERROR: %d\n", ret); return ret);
  ret = aclrtCreateStream(stream);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclrtCreateStream failed. ERROR: %d\n", ret); return ret);
  return 0;
}

template <typename T>
int CreateAclTensor(const std::vector<T>& hostData, const std::vector<int64_t>& shape, void** deviceAddr,
                    aclDataType dataType, aclTensor** tensor) {
  auto size = GetShapeSize(shape) * sizeof(T);
  // 调用aclrtMalloc申请device侧内存
  auto ret = aclrtMalloc(deviceAddr, size, ACL_MEM_MALLOC_HUGE_FIRST);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclrtMalloc failed. ERROR: %d\n", ret); return ret);
  // 调用aclrtMemcpy将host侧数据拷贝到device侧内存上
  ret = aclrtMemcpy(*deviceAddr, size, hostData.data(), size, ACL_MEMCPY_HOST_TO_DEVICE);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclrtMemcpy failed. ERROR: %d\n", ret); return ret);

  // 计算连续tensor的strides
  std::vector<int64_t> strides(shape.size(), 1);
  for (int64_t i = shape.size() - 2; i >= 0; i--) {
    strides[i] = shape[i + 1] * strides[i + 1];
  }

  // 调用aclCreateTensor接口创建aclTensor
  *tensor = aclCreateTensor(shape.data(), shape.size(), dataType, strides.data(), 0, aclFormat::ACL_FORMAT_ND,
                            shape.data(), shape.size(), *deviceAddr);
  return 0;
}

static inline std::string JoinPath(const std::string& dir, const std::string& file) {
  if (dir.empty()) {
    return file;
  }
  const char last = dir.back();
  if (last == '/' || last == '\\') {
    return dir + file;
  }
  return dir + "/" + file;
}

static bool EnsureDirExists(const std::string& dir) {
  if (dir.empty()) {
    return false;
  }
#ifdef _WIN32
  const int rc = _mkdir(dir.c_str());
#else
  const int rc = mkdir(dir.c_str(), 0755);
#endif
  if (rc == 0) {
    return true;
  }
  if (errno == EEXIST) {
    return true;
  }
  LOG_PRINT("Failed to create dir: %s (errno=%d)\n", dir.c_str(), errno);
  return false;
}

template <typename T>
static bool ReadBin(const std::string& path, std::vector<T>* out, int64_t expectedElems) {
  if (out == nullptr || expectedElems < 0) {
    return false;
  }
  std::ifstream fin(path, std::ios::binary);
  if (!fin) {
    LOG_PRINT("Failed to open for read: %s\n", path.c_str());
    return false;
  }
  fin.seekg(0, std::ios::end);
  const std::streamoff fileSize = fin.tellg();
  fin.seekg(0, std::ios::beg);
  const int64_t expectedBytes = expectedElems * static_cast<int64_t>(sizeof(T));
  if (expectedBytes != static_cast<int64_t>(fileSize)) {
    LOG_PRINT("File size mismatch: %s (got %lld bytes, expected %lld bytes)\n",
              path.c_str(), static_cast<long long>(fileSize), static_cast<long long>(expectedBytes));
    return false;
  }
  out->resize(static_cast<size_t>(expectedElems));
  fin.read(reinterpret_cast<char*>(out->data()), static_cast<std::streamsize>(expectedBytes));
  if (!fin) {
    LOG_PRINT("Failed to read file: %s\n", path.c_str());
    return false;
  }
  return true;
}

template <typename T>
bool WriteBin(const std::string& path, const std::vector<T>& data) {
  std::ofstream fout(path, std::ios::binary);
  if (!fout) {
    LOG_PRINT("Failed to open for write: %s\n", path.c_str());
    return false;
  }
  const size_t bytes = data.size() * sizeof(T);
  fout.write(reinterpret_cast<const char*>(data.data()), static_cast<std::streamsize>(bytes));
  if (!fout) {
    LOG_PRINT("Failed to write file: %s\n", path.c_str());
    return false;
  }
  return true;
}

// NOTE: CPU reference/compare is intentionally done in external scripts (torch_ref.py / compare_case.py),
// not in this C++ example. This binary focuses on running the device op and dumping inputs/outputs to .bin.

static void DumpMetaTxt(const std::string& dir,
                        int64_t batch_size,
                        int64_t total_seqlen,
                        int64_t dim,
                        int64_t width,
                        int64_t activationMode,
                        int64_t padSlotId) {
  const std::string path = JoinPath(dir, "meta.txt");
  std::ofstream fout(path);
  if (!fout) {
    LOG_PRINT("Failed to write meta: %s\n", path.c_str());
    return;
  }
  fout << "batch_size=" << batch_size << "\n";
  fout << "total_seqlen=" << total_seqlen << "\n";
  fout << "dim=" << dim << "\n";
  fout << "width=" << width << "\n";
  fout << "activation_mode=" << activationMode << "\n";
  fout << "pad_slot_id=" << padSlotId << "\n";
  fout << "file_float_dtype=float32\n";
  fout << "note=All float tensors are stored as float32 .bin; values are expected to be fp16-quantized by producers.\n";
}

int main(int argc, char** argv) {
  if (argc > 1 && argv[1] != nullptr) {
    const std::string arg1(argv[1]);
    if (arg1 == "-h" || arg1 == "--help") {
      PrintUsage((argc > 0) ? argv[0] : nullptr);
      return 0;
    }
  }

  // 0. Hard-coded parameters (no CLI input).
  constexpr int64_t batch_size = 32;
  constexpr int64_t dim = 1024;
  constexpr int64_t total_seqlen = 8192;  // 总序列长度（varlen：所有序列长度之和）
  constexpr int64_t width = 4;            // 卷积核宽度
  constexpr int64_t maxPrintSeqs = 2;     // 仅打印前N个序列的conv_states，避免batch较大时输出过多
  constexpr int64_t initStateSeqs = 1;    // 前N个序列使用初始状态（has_initial_state=1）
  constexpr int64_t activationMode = 1;   // 1 = SiLU/Swish, 0 = None
  constexpr int64_t padSlotId = -1;       // -1表示无pad slot
  std::string caseDir = "./case";
  const char* envCaseDir = std::getenv("CAUSAL_CONV1D_CASE_DIR");
  if (envCaseDir != nullptr && envCaseDir[0] != '\0') {
    caseDir = envCaseDir;
  }

  CHECK_RET(batch_size > 0 && dim > 0 && total_seqlen > 0, LOG_PRINT("Invalid hard-coded sizes\n"); return 1);
  CHECK_RET(initStateSeqs >= 0 && initStateSeqs <= batch_size,
            LOG_PRINT("initStateSeqs must be in [0, batch_size] (got %ld, batch_size=%ld)\n",
                      initStateSeqs, batch_size);
            return 1);
  CHECK_RET(total_seqlen <= static_cast<int64_t>(std::numeric_limits<int32_t>::max()),
            LOG_PRINT("total_seqlen too large for int32 query_start_loc (got %ld)\n", total_seqlen);
            return 1);
  CHECK_RET(width == 4, LOG_PRINT("width must be 4 for this example (got %ld)\n", width); return 1);
  CHECK_RET(EnsureDirExists(caseDir), LOG_PRINT("Failed to create output dir: %s\n", caseDir.c_str()); return 1);

  // 1. （固定写法）device/stream初始化，参考AscendCL对外接口列表
  // 根据自己的实际device填写deviceId
  int32_t deviceId = 0;
  aclrtStream stream;
  auto ret = Init(deviceId, &stream);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("Init acl failed. ERROR: %d\n", ret); return ret);

  // 2. 构造输入与输出，需要根据API的接口自定义构造
  // x: (total_seqlen, dim) - varlen输入
  std::vector<int64_t> xShape = {total_seqlen, dim};
  // Fill x with a token-identifiable pattern so ring slot/prefetch order can be verified from kernel dumps,
  // while keeping output finite in fp16:
  //   x[t, :] = (t + 1) / total_seqlen   in (0, 1]
  std::vector<op::fp16_t> xHostData(GetShapeSize(xShape), 0);

  // weight: (width, dim) - 卷积权重
  std::vector<int64_t> weightShape = {width, dim};
  // Use an identifiable pattern so LoadWeightAndBias can be validated from kernel dumps:
  //   weight[j, c] = c + j * 200
  // With dim=1024 and dimTileSize=512, expected dumps:
  //   c0=0   -> [0..7], [200..207], [400..407], [600..607]
  //   c0=512 -> [512..519], [712..719], [912..919], [1112..1119]
  std::vector<op::fp16_t> weightHostData(GetShapeSize(weightShape), 0);

  // bias: (dim,) - 可选偏置
  std::vector<int64_t> biasShape = {dim};
  // bias[c] = 1000 + c, so dumps should be:
  //   c0=0   -> [1000..1007]
  //   c0=512 -> [1512..1519]
  std::vector<op::fp16_t> biasHostData(GetShapeSize(biasShape), 0);

  // convStates: (num_cache_lines, state_len, dim) - 卷积状态
  std::vector<int64_t> convStatesShape = {batch_size, width - 1, dim};
  std::vector<op::fp16_t> convStatesHostData(GetShapeSize(convStatesShape), 0);
  // Fill initial state for the first N sequences with an identifiable pattern, matching OPERATOR_SPEC.md:
  //   conv_states[cache=seq, pos, c] represents {h-3, h-2, h-1} when pos={0,1,2}.
  // Scale down values to keep output finite in fp16 when weight is large:
  //   raw = (pos+1) * 10000 + seq*100 + c
  //   conv_states = raw / 10000

  // queryStartLoc: (batch_size + 1,) - 序列起始位置
  std::vector<int64_t> queryStartLocShape = {batch_size + 1};
  // Split `total_seqlen` into `batch_size` sequences (varlen mode).
  std::vector<int32_t> queryStartLocHostData(static_cast<size_t>(batch_size + 1), 0);

  // cacheIndices: (batch_size,) - 缓存索引
  std::vector<int64_t> cacheIndicesShape = {batch_size};
  std::vector<int32_t> cacheIndicesHostData(static_cast<size_t>(batch_size), 0);

  // hasInitialState: (batch_size,) - 是否有初始状态
  std::vector<int64_t> hasInitialStateShape = {batch_size};
  std::vector<uint8_t> hasInitialStateHostData(static_cast<size_t>(batch_size), static_cast<uint8_t>(0));

  // Load inputs from caseDir (float32 .bin for floats; int32/uint8 for indices/bools).
  std::vector<float> xF32;
  std::vector<float> wF32;
  std::vector<float> bF32;
  std::vector<float> sF32;

  const int64_t xElems = GetShapeSize(xShape);
  const int64_t wElems = GetShapeSize(weightShape);
  const int64_t bElems = GetShapeSize(biasShape);
  const int64_t sElems = GetShapeSize(convStatesShape);
  const int64_t qslElems = GetShapeSize(queryStartLocShape);
  const int64_t ciElems = GetShapeSize(cacheIndicesShape);
  const int64_t hisElems = GetShapeSize(hasInitialStateShape);

  CHECK_RET(ReadBin<float>(JoinPath(caseDir, "x.bin"), &xF32, xElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "x.bin").c_str()); return 1);
  CHECK_RET(ReadBin<float>(JoinPath(caseDir, "weight.bin"), &wF32, wElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "weight.bin").c_str()); return 1);
  CHECK_RET(ReadBin<float>(JoinPath(caseDir, "bias.bin"), &bF32, bElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "bias.bin").c_str()); return 1);
  CHECK_RET(ReadBin<float>(JoinPath(caseDir, "conv_states.bin"), &sF32, sElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "conv_states.bin").c_str()); return 1);
  CHECK_RET(ReadBin<int32_t>(JoinPath(caseDir, "query_start_loc.bin"), &queryStartLocHostData, qslElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "query_start_loc.bin").c_str()); return 1);
  CHECK_RET(ReadBin<int32_t>(JoinPath(caseDir, "cache_indices.bin"), &cacheIndicesHostData, ciElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "cache_indices.bin").c_str()); return 1);
  CHECK_RET(ReadBin<uint8_t>(JoinPath(caseDir, "has_initial_state.bin"), &hasInitialStateHostData, hisElems),
            LOG_PRINT("Missing/invalid input: %s\n", JoinPath(caseDir, "has_initial_state.bin").c_str()); return 1);

  for (int64_t i = 0; i < xElems; ++i) {
    xHostData[static_cast<size_t>(i)] = static_cast<op::fp16_t>(xF32[static_cast<size_t>(i)]);
  }
  for (int64_t i = 0; i < wElems; ++i) {
    weightHostData[static_cast<size_t>(i)] = static_cast<op::fp16_t>(wF32[static_cast<size_t>(i)]);
  }
  for (int64_t i = 0; i < bElems; ++i) {
    biasHostData[static_cast<size_t>(i)] = static_cast<op::fp16_t>(bF32[static_cast<size_t>(i)]);
  }
  for (int64_t i = 0; i < sElems; ++i) {
    convStatesHostData[static_cast<size_t>(i)] = static_cast<op::fp16_t>(sF32[static_cast<size_t>(i)]);
  }

  // y: (total_seqlen, dim) - 输出
  std::vector<int64_t> yShape = {total_seqlen, dim};
  std::vector<op::fp16_t> yHostData(GetShapeSize(yShape), 0);

  // 创建device侧tensor
  void* xDeviceAddr = nullptr;
  void* weightDeviceAddr = nullptr;
  void* biasDeviceAddr = nullptr;
  void* convStatesDeviceAddr = nullptr;
  void* queryStartLocDeviceAddr = nullptr;
  void* cacheIndicesDeviceAddr = nullptr;
  void* hasInitialStateDeviceAddr = nullptr;
  void* yDeviceAddr = nullptr;

  aclTensor* x = nullptr;
  aclTensor* weight = nullptr;
  aclTensor* bias = nullptr;
  aclTensor* convStates = nullptr;
  aclTensor* queryStartLoc = nullptr;
  aclTensor* cacheIndices = nullptr;
  aclTensor* hasInitialState = nullptr;
  aclTensor* y = nullptr;

  ret = CreateAclTensor(xHostData, xShape, &xDeviceAddr, aclDataType::ACL_FLOAT16, &x);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(weightHostData, weightShape, &weightDeviceAddr, aclDataType::ACL_FLOAT16, &weight);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(biasHostData, biasShape, &biasDeviceAddr, aclDataType::ACL_FLOAT16, &bias);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(convStatesHostData, convStatesShape, &convStatesDeviceAddr, aclDataType::ACL_FLOAT16, &convStates);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(queryStartLocHostData, queryStartLocShape, &queryStartLocDeviceAddr, aclDataType::ACL_INT32, &queryStartLoc);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(cacheIndicesHostData, cacheIndicesShape, &cacheIndicesDeviceAddr, aclDataType::ACL_INT32, &cacheIndices);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(hasInitialStateHostData, hasInitialStateShape, &hasInitialStateDeviceAddr, aclDataType::ACL_BOOL, &hasInitialState);
  CHECK_RET(ret == ACL_SUCCESS, return ret);
  ret = CreateAclTensor(yHostData, yShape, &yDeviceAddr, aclDataType::ACL_FLOAT16, &y);
  CHECK_RET(ret == ACL_SUCCESS, return ret);

  // 算子参数（activationMode/padSlotId）已在参数解析阶段确定

  // 3. 调用CANN算子库API
  uint64_t workspaceSize = 0;
  aclOpExecutor* executor;

  // 调用aclnnCausalConv1d第一段接口
  ret = aclnnCausalConv1dGetWorkspaceSize(
            x, weight, bias, convStates, queryStartLoc, cacheIndices, hasInitialState,
            activationMode, padSlotId, y, &workspaceSize, &executor);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclnnCausalConv1dGetWorkspaceSize failed. ERROR: %d\n", ret); return ret);

  // 根据第一段接口计算出的workspaceSize申请device内存
  void* workspaceAddr = nullptr;
  if (workspaceSize > 0) {
    ret = aclrtMalloc(&workspaceAddr, workspaceSize, ACL_MEM_MALLOC_HUGE_FIRST);
    CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("allocate workspace failed. ERROR: %d\n", ret); return ret);
  }

  // 调用aclnnCausalConv1d第二段接口
  ret = aclnnCausalConv1d(workspaceAddr, workspaceSize, executor, stream);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclnnCausalConv1d failed. ERROR: %d\n", ret); return ret);

  // 4. （固定写法）同步等待任务执行结束
  ret = aclrtSynchronizeStream(stream);
  CHECK_RET(ret == ACL_SUCCESS, LOG_PRINT("aclrtSynchronizeStream failed. ERROR: %d\n", ret); return ret);

  // 5. 获取输出的值，将device侧内存上的结果拷贝至host侧
  LOG_PRINT("Output y (first 10 elements):\n");
  const auto yResult = CopyDeviceToHost<op::fp16_t>(yShape, yDeviceAddr);
  CHECK_RET(!yResult.empty(), return 1);
  PrintFirstN("y[c=0]", yResult, 0, 10);
  if (dim >= 512 + 10) {
    PrintFirstN("y[c=512]", yResult, 512, 10);
  }

  LOG_PRINT("\nConv states (per pos, first 10 elements):\n");
  const auto convStatesResult = CopyDeviceToHost<op::fp16_t>(convStatesShape, convStatesDeviceAddr);
  CHECK_RET(!convStatesResult.empty(), return 1);
  const int64_t stateLen = width - 1;
  const int64_t printSeqs = std::min(batch_size, maxPrintSeqs);
  if (printSeqs > 0) {
    for (int64_t seq = 0; seq < printSeqs; ++seq) {
      for (int64_t pos = 0; pos < stateLen; ++pos) {
        const int64_t base = (seq * stateLen + pos) * dim;
        const std::string labelBase =
            "conv_states[s=" + std::to_string(seq) + ",pos=" + std::to_string(pos) + ",c=0]";
        PrintFirstN(labelBase, convStatesResult, base, 10);
        if (dim >= 512 + 10) {
          const std::string labelHalf =
              "conv_states[s=" + std::to_string(seq) + ",pos=" + std::to_string(pos) + ",c=512]";
          PrintFirstN(labelHalf, convStatesResult, base + 512, 10);
        }
      }
    }
    if (printSeqs < batch_size) {
      LOG_PRINT("... (conv_states print skipped for %ld sequences)\n", batch_size - printSeqs);
    }
  }

  // 5. Dump inputs/outputs in a Python-friendly format (float32 .bin).
  DumpMetaTxt(caseDir, batch_size, total_seqlen, dim, width, activationMode, padSlotId);

  auto fp16ToF32 = [](const std::vector<op::fp16_t>& in) -> std::vector<float> {
    std::vector<float> out(in.size(), 0.0f);
    for (size_t i = 0; i < in.size(); ++i) {
      out[i] = static_cast<float>(in[i]);
    }
    return out;
  };

  (void)WriteBin<float>(JoinPath(caseDir, "x.bin"), fp16ToF32(xHostData));
  (void)WriteBin<float>(JoinPath(caseDir, "weight.bin"), fp16ToF32(weightHostData));
  (void)WriteBin<float>(JoinPath(caseDir, "bias.bin"), fp16ToF32(biasHostData));
  (void)WriteBin<float>(JoinPath(caseDir, "conv_states.bin"), fp16ToF32(convStatesHostData));
  (void)WriteBin<int32_t>(JoinPath(caseDir, "query_start_loc.bin"), queryStartLocHostData);
  (void)WriteBin<int32_t>(JoinPath(caseDir, "cache_indices.bin"), cacheIndicesHostData);
  (void)WriteBin<uint8_t>(JoinPath(caseDir, "has_initial_state.bin"), hasInitialStateHostData);

  (void)WriteBin<float>(JoinPath(caseDir, "y_device.bin"), fp16ToF32(yResult));
  (void)WriteBin<float>(JoinPath(caseDir, "conv_states_device.bin"), fp16ToF32(convStatesResult));

  // 6. 释放aclTensor
  aclDestroyTensor(x);
  aclDestroyTensor(weight);
  aclDestroyTensor(bias);
  aclDestroyTensor(convStates);
  aclDestroyTensor(queryStartLoc);
  aclDestroyTensor(cacheIndices);
  aclDestroyTensor(hasInitialState);
  aclDestroyTensor(y);

  // 7. 释放device资源
  aclrtFree(xDeviceAddr);
  aclrtFree(weightDeviceAddr);
  aclrtFree(biasDeviceAddr);
  aclrtFree(convStatesDeviceAddr);
  aclrtFree(queryStartLocDeviceAddr);
  aclrtFree(cacheIndicesDeviceAddr);
  aclrtFree(hasInitialStateDeviceAddr);
  aclrtFree(yDeviceAddr);
  if (workspaceSize > 0) {
    aclrtFree(workspaceAddr);
  }
  aclrtDestroyStream(stream);
  aclrtResetDevice(deviceId);
  aclFinalize();

  LOG_PRINT("\nTest completed successfully!\n");
  return 0;
}
