/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/*!
 * \file ts_mla_preprocess_v2_tc.cpp
 * \brief MlaPreprocessV2用例.
 */

#include "ts_mla_preprocess_v2.h"
class Ts_MlaPreprocessV2_Ascend910B2_Case : public Ts_MlaPreprocessV2_WithParam_Ascend910B2 {};

TEST_P(Ts_MlaPreprocessV2_Ascend910B2_Case, general_case)
{
    ASSERT_TRUE(case_->Init());
    ASSERT_EQ(case_->Run(), case_->mOpInfo.mExp.mSuccess);
}

const auto Tc_MlaPreprocessV2_General_Case = ::testing::Values(
    //---nd_nd_nd
    MlaPreprocessV2Case("case_fp16_cm0_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, true, ge::DataType::DT_FLOAT16, true, true, true)),
    //---nd_nd_nz
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, true, false)),
    //---nd_nz_nd
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, true)),
    //---nd_nz_nz
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm0_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, true, false, false)),
    //---nz_nd_nd
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, true)),
    //---nz_nd_nz
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, true, false)),
    //---nz_nz_nd
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, true)),
    //---nz_nz_nz
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm0_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm1_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm2_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    MlaPreprocessCaseV2("case_fp16_cm3_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_FLOAT16, false, false, false)),
    // ----bf16----
    //---nd_nd_nd
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, true)),
    //---nd_nd_nz
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, true, false)),
    //---nd_nz_nd
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, true)),
    //---nd_nz_nz
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm0_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nd_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, true, false, false)),
    //---nz_nd_nd
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nd_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nd_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, true)),
    //---nz_nd_nz
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nd_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nd_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, true, false)),
    //---nz_nz_nd
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nz_nd_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nz_nd_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, true)),
    //---nz_nz_nz
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nz_nz_qm0", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 0,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm2_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 2, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
    MlaPreprocessCaseV2("case_bf16_cm3_nz_nz_nz_qm1", true, "dbginfo",
                      OpInfo(ControlInfo(true, true),
                             ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
                      MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 3, 1,
                                               true, 1, true, ge::DataType::DT_BF16, false, false, false)),
//     // ---- noquant----
//     MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nz_qm0_no_quant", true, "dbginfo",
//                       OpInfo(ControlInfo(true, true),
//                              ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
//                       MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
//                                                false, 1, true, ge::DataType::DT_BF16, false, false, false)),
//     MlaPreprocessCaseV2("case_bf16_cm0_nz_nz_nd_qm0_no_quant", true, "dbginfo",
//                       OpInfo(ControlInfo(true, true),
//                              ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
//                       MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 0, 0,
//                                                false, 1, true, ge::DataType::DT_BF16, false, false, true)),
//     MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nz_qm0_no_quant", true, "dbginfo",
//                       OpInfo(ControlInfo(true, true),
//                              ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
//                       MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
//                                                false, 1, true, ge::DataType::DT_BF16, false, false, false)),
//     MlaPreprocessCaseV2("case_bf16_cm1_nz_nz_nd_qm0_no_quant", true, "dbginfo",
//                       OpInfo(ControlInfo(true, true),
//                              ExpectInfo(true, ExpectInfo::kInvalidTilingKey, ExpectInfo::kInvalidTilingBlockDim)),
//                       MlaPreprocessCaseV2::Param(4, 7168, 32, 192, 128, 128, 0, 0, 1e-5f, 2, 2, true, true, true, 1, 0,
//                                                false, 1, true, ge::DataType::DT_BF16, false, false, true))
);

INSTANTIATE_TEST_SUITE_P(MlaPreprocessV2, Ts_MlaPreprocessV2_Ascend910B2_Case, Tc_MlaPreprocessV2_General_Case);