#!/usr/bin/python
# -*- coding: utf-8 -*-
# This program is free software, you can redistribute it and/or modify.
# Copyright (c) 2025 Huawei Technologies Co., Ltd.
# This file is a part of the CANN Open Software.
# Licensed under CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ======================================================================================================================

import torch

# 定义测试参数组合
TEST_PARAMS = {
    "Prefill0":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [8192],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [0],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "Prefill1":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [8192],
        "head_dim": [128],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [0],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "Prefill2":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [8192],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [128],
        "coff": [1],
        "norm_eps": [1e-6],
        "start_p": [0],
        "rotary_mode": [2],
        "layout_x": ["TH"],#TH BSH
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode0":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [1],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [8192, 8195],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode1":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [1],
        "head_dim": [128],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [8192, 8195],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode2":{
        "batch_size": [1],
        "hidden_size": [4096],
        "Seq_len": [1],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [128],
        "coff": [1],
        "norm_eps": [1e-6],
        "start_p": [8192, 8195],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode3":{
        "batch_size": [8],
        "hidden_size": [4096],
        "Seq_len": [3],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [8193],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode4":{
        "batch_size": [8],
        "hidden_size": [4096],
        "Seq_len": [3],
        "head_dim": [128],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [4],
        "coff": [2],
        "norm_eps": [1e-6],
        "start_p": [8192, 8193, 8191],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    },
    "decode5":{
        "batch_size": [8],
        "hidden_size": [4096],
        "Seq_len": [3],
        "head_dim": [512],
        "block_size": [128],
        "rope_head_dim": [64],
        "cmp_ratio": [128],
        "coff": [1],
        "norm_eps": [1e-6],
        "start_p": [8193],
        "rotary_mode": [2],
        "layout_x": ["TH"],
        "data_type": [torch.bfloat16],
        "cu_seqlens":[None],
        "seqused":[None],
        "start_pos": [None],
    }
}#注意单个用例组内的用例尽量不要超过32
FIRST_CASE = [TEST_PARAMS["Prefill0"], TEST_PARAMS["Prefill1"], TEST_PARAMS["Prefill2"], TEST_PARAMS["decode0"],
            TEST_PARAMS["decode1"], TEST_PARAMS["decode2"], TEST_PARAMS["decode3"], TEST_PARAMS["decode4"], 
            TEST_PARAMS["decode5"]]
# 按需选择要启用的测试参数（例如默认启用所有）
ENABLED_PARAMS = FIRST_CASE #按需增加需要的case即可