/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file allto_all_matmul_tiling_key.h
 * \brief
 */

#ifndef __OP_KERNEL_ALLTO_ALL_MATMUL_TILING_KEY_H__
#define __OP_KERNEL_ALLTO_ALL_MATMUL_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define TILINGKEY_TPL_FP16 0
#define TILINGKEY_TPL_BF16 1
#define TILINGKEY_TPL_FP32 2
#define TILINGKEY_TPL_NOQUANT 0
#define TILINGKEY_TPL_A16W8 1
#define TILINGKEY_TPL_A4W4 2

// 模板参数
ASCENDC_TPL_ARGS_DECL(
    AlltoAllMatmul, // 算子OpType
    ASCENDC_TPL_BOOL_DECL(ALLTO_ALL_MM_HAS_BIAS, 0, 1),
    ASCENDC_TPL_BOOL_DECL(ALLTO_ALL_MM_TRANSPOSE_X2, 0, 1),
    ASCENDC_TPL_UINT_DECL(ALLTO_ALL_MM_QUANT_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_NOQUANT, TILINGKEY_TPL_A16W8, TILINGKEY_TPL_A4W4),
    ASCENDC_TPL_UINT_DECL(ALLTO_ALL_MM_QUANT_BIAS_DTYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_FP16, TILINGKEY_TPL_BF16, TILINGKEY_TPL_FP32)
);

// 模板参数组合
// 用于调用GET_TPL_TILING_KEY获取TilingKey时，接口内部校验TilingKey是否合法
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(  // 无quant，不需要指定bias类别
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_HAS_BIAS, 0, 1),
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_TRANSPOSE_X2, 0, 1),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_TYPE, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_NOQUANT),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_BIAS_DTYPE, ASCENDC_TPL_UI_LIST, 0)),
    ASCENDC_TPL_ARGS_SEL(  // 有bias，A16W8，需要指定bias类别
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_HAS_BIAS, 1),
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_TRANSPOSE_X2, 0, 1),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_TYPE, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_A16W8),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_BIAS_DTYPE, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_FP16, TILINGKEY_TPL_BF16, TILINGKEY_TPL_FP32)),
    ASCENDC_TPL_ARGS_SEL(  // 有bias，x1不需要被量化，矩阵乘法为int4，需要指定bias类别
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_HAS_BIAS, 1),
        ASCENDC_TPL_BOOL_SEL(ALLTO_ALL_MM_TRANSPOSE_X2, 0, 1),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_TYPE, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_A4W4),
        ASCENDC_TPL_UINT_SEL(ALLTO_ALL_MM_QUANT_BIAS_DTYPE, ASCENDC_TPL_UI_LIST, TILINGKEY_TPL_FP16, TILINGKEY_TPL_BF16, TILINGKEY_TPL_FP32))
);
#endif // __OP_KERNEL_ALLTO_ALL_MATMUL_TILING_KEY_H__